type Word = {
  word: string;
  hint: string;
};

export type WordData = {
  [category: string]: Word[];
};

export const words: WordData = {
  "yrken": [
      { "word": "Kirurg", "hint": "Precision" },
      { "word": "Brandman", "hint": "Hetta" },
      { "word": "Bibliotekarie", "hint": "Tystnad" },
      { "word": "Snickare", "hint": "Struktur" },
      { "word": "Pilot", "hint": "Höjd" },
      { "word": "Kock", "hint": "Smak" },
      { "word": "Lantbrukare", "hint": "Skörd" },
      { "word": "Polis", "hint": "Ordning" },
      { "word": "Journalist", "hint": "Källor" },
      { "word": "Frisör", "hint": "Krona" },
      { "word": "Elektriker", "hint": "Spänning" },
      { "word": "Läkare", "hint": "Puls" },
      { "word": "Lärare", "hint": "Kunskap" },
      { "word": "Arkitekt", "hint": "Ritning" },
      { "word": "Mekaniker", "hint": "Friktion" },
      { "word": "Sjöman", "hint": "Våg" },
      { "word": "Astronaut", "hint": "Vakuum" },
      { "word": "Advokat", "hint": "Paragraf" },
      { "word": "Dansare", "hint": "Rytm" },
      { "word": "Busschaufför", "hint": "Rutt" }
    ],
    "djur": [
      { "word": "Elefant", "hint": "Minne" },
      { "word": "Pingvin", "hint": "Kyla" },
      { "word": "Giraff", "hint": "Utblick" },
      { "word": "Lejon", "hint": "Stolthet" },
      { "word": "Blåval", "hint": "Eko" },
      { "word": "Kamel", "hint": "Uthållighet" },
      { "word": "Känguru", "hint": "Språng" },
      { "word": "Igelkott", "hint": "Försvar" },
      { "word": "Uggla", "hint": "Vaksamhet" },
      { "word": "Panda", "hint": "Kontrast" },
      { "word": "Haj", "hint": "Rörelse" },
      { "word": "Krokodil", "hint": "Lurpass" },
      { "word": "Häst", "hint": "Galopp" },
      { "word": "Örn", "hint": "Skärpa" },
      { "word": "Gepard", "hint": "Acceleration" },
      { "word": "Bläckfisk", "hint": "Kamouflage" },
      { "word": "Räv", "hint": "List" },
      { "word": "Fladdermus", "hint": "Sonar" },
      { "word": "Sköldpadda", "hint": "Tid" },
      { "word": "Varg", "hint": "Flock" }
    ],
    "frukter_och_gront": [
      { "word": "Ananas", "hint": "Tagg" },
      { "word": "Avokado", "hint": "Kärna" },
      { "word": "Broccoli", "hint": "Förgrening" },
      { "word": "Banan", "hint": "Böjning" },
      { "word": "Vattenmelon", "hint": "Sötma" },
      { "word": "Citron", "hint": "Syra" },
      { "word": "Aubergine", "hint": "Glans" },
      { "word": "Kiwi", "hint": "Ludd" },
      { "word": "Majs", "hint": "Rad" },
      { "word": "Granatäpple", "hint": "Juvel" },
      { "word": "Apelsin", "hint": "Klyfta" },
      { "word": "Äpple", "hint": "Frestelse" },
      { "word": "Gurka", "hint": "Vätska" },
      { "word": "Tomat", "hint": "Mjukhet" },
      { "word": "Morot", "hint": "Rot" },
      { "word": "Spenat", "hint": "Järn" },
      { "word": "Jordgubbe", "hint": "Sommar" },
      { "word": "Mango", "hint": "Tropik" },
      { "word": "Persika", "hint": "Sammet" },
      { "word": "Vitlök", "hint": "Doft" }
    ],
    "sport": [
      { "word": "Fotboll", "hint": "Gräs" },
      { "word": "Ishockey", "hint": "Kyla" },
      { "word": "Tennis", "hint": "Serve" },
      { "word": "Simning", "hint": "Motstånd" },
      { "word": "Basket", "hint": "Nät" },
      { "word": "Golf", "hint": "Precision" },
      { "word": "Skidåkning", "hint": "Lutning" },
      { "word": "Boxning", "hint": "Garde" },
      { "word": "Ridning", "hint": "Balans" },
      { "word": "Padel", "hint": "Vägg" },
      { "word": "Innebandy", "hint": "Plast" },
      { "word": "Handboll", "hint": "Klister" },
      { "word": "Friidrott", "hint": "Gräns" },
      { "word": "Segling", "hint": "Vind" },
      { "word": "Cykel", "hint": "Trampa" },
      { "word": "Volleyboll", "hint": "Luft" },
      { "word": "Bågskytte", "hint": "Fokus" },
      { "word": "Klättring", "hint": "Grepp" },
      { "word": "Bowling", "hint": "Kägla" },
      { "word": "Gymnastik", "hint": "Vighet" }
    ],
    "saker": [
      { "word": "Klocka", "hint": "Tid" },
      { "word": "Paraply", "hint": "Skydd" },
      { "word": "Glasögon", "hint": "Lins" },
      { "word": "Spegel", "hint": "Reflektion" },
      { "word": "Kamera", "hint": "Slutare" },
      { "word": "Plånbok", "hint": "Värde" },
      { "word": "Nyckel", "hint": "Tillträde" },
      { "word": "Ryggsäck", "hint": "Vikt" },
      { "word": "Telefon", "hint": "Kontakt" },
      { "word": "Tandborste", "hint": "Emalj" },
      { "word": "Hammare", "hint": "Kraft" },
      { "word": "Lampa", "hint": "Ljus" },
      { "word": "Sax", "hint": "Snitt" },
      { "word": "Kudde", "hint": "Vila" },
      { "word": "Stol", "hint": "Stöd" },
      { "word": "Tidning", "hint": "Blad" },
      { "word": "Ficklampa", "hint": "Stråle" },
      { "word": "Halsband", "hint": "Länk" },
      { "word": "Kastrull", "hint": "Sjud" },
      { "word": "Cykelhjälm", "hint": "Säkerhet" }
    ]
};
